### ISSUE TITLE
GUI: Clicking into dice textfield clears any and all numbers

### ISSUE THREAD

**Issue by mshannahnv** [anderspitman/dice-game#82]
Clicking into textfield clears any and all numbers. If a user accidentally clicks into it, they may not want their number deleted. May be better to let them delete their own numbers if they'd like to.

**Comment by ngdao** [comment]
I was thinking it would be more convenient to reset the number when the textfield is clicked because the only purpose to click the textfield is to change the number of dice. They're more likely to click it on purpose. And accidentally clicking it and have it reset is a very small price. What do you think?
